#!/usr/bin/env bash
# generate-bridges.sh — Parse skills/ front-matter, update AGENTS.md skill index + Kiro bridge.
# Run from KB root, or pass KB_ROOT as first argument.

set -euo pipefail

KB_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
SKILLS_DIR="$KB_ROOT/skills"
AGENTS_FILE="$KB_ROOT/AGENTS.md"

# --- Parse skills front-matter ---
declare -a ROWS=()

for file in "$SKILLS_DIR"/*.md; do
  [ -f "$file" ] || continue
  basename="$(basename "$file")"

  title=$(sed -n '/^---$/,/^---$/{
    /^title:/{
      s/^title: *//
      s/^"//; s/"$//
      p
    }
  }' "$file")
  trigger=$(sed -n '/^---$/,/^---$/{
    /^trigger:/{
      s/^trigger: *//
      s/^"//; s/"$//
      p
    }
  }' "$file")

  [ -z "$title" ] && title="$basename"
  [ -z "$trigger" ] && trigger="(no trigger defined)"

  ROWS+=("| ${title} | \`${basename}\` | ${trigger} |")
done

# --- Build skill index table ---
SKILL_TABLE="| Skill | File | Trigger |
|---|---|---|"
for row in "${ROWS[@]}"; do
  SKILL_TABLE="$SKILL_TABLE
$row"
done

# --- Update AGENTS.md between markers ---
BEGIN_MARKER="<!-- AUTO-GENERATED by ./scripts/generate-bridges.sh — do not edit manually -->"
END_MARKER="<!-- END SKILL INDEX -->"

if grep -q "$BEGIN_MARKER" "$AGENTS_FILE"; then
  TABLE_FILE=$(mktemp)
  printf '%s' "$SKILL_TABLE" > "$TABLE_FILE"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v tfile="$TABLE_FILE" '
    $0 == begin { print; printf "\nThese files live in `skills/`. Read the relevant one when the trigger matches.\n\n"; while ((getline line < tfile) > 0) print line; printf "\n"; skip=1; next }
    $0 == end { skip=0; print; next }
    !skip { print }
  ' "$AGENTS_FILE" > "$AGENTS_FILE.tmp" && mv "$AGENTS_FILE.tmp" "$AGENTS_FILE"
  rm -f "$TABLE_FILE"
  echo "✓ AGENTS.md skill index updated (${#ROWS[@]} skills)"
else
  echo "✗ Markers not found in AGENTS.md — run initialize-kb first"
  exit 1
fi

# --- Kiro CLI bridge (lives outside repo, needs absolute path) ---
if [ -d "$HOME/.kiro" ]; then
  KIRO_DIR="$HOME/.kiro/skills/worktrail"
  mkdir -p "$KIRO_DIR"
  cat > "$KIRO_DIR/SKILL.md" << EOF
---
name: worktrail
description: |
  Personal knowledge base. Load on EVERY session start.
  Contains daily tasks, project tracking, people notes, and reusable skills.
  Skills trigger on specific intents — read the index below to route correctly.
---

## KB Root

\`$KB_ROOT\`

All paths below are relative to this root unless fully qualified.

## Boot Sequence

At the start of every session, read these two files (do NOT skip):

1. \`profile.md\` — role, team, tools config, repo paths
2. \`AGENTS.md\` — decision flow, file creation rules, skill index

## Skill Index

These files live in \`skills/\`. Read the relevant one when the trigger matches.

$SKILL_TABLE

Only read a skill file when its trigger matches. Don't load all of them upfront.

## Key Paths

- Daily tasks: \`daily-tasks/{YYYY}/{MM}/{YYYY-MM-DD}.md\`
- Active projects: \`projects/working-on/{slug}/\`
- People notes: \`people/{slug}.md\`

## Rules

- Never log credentials to worktrail files — display in chat only
- Resolve current date via \`date\` before creating dated files
- After every ~10 file ops, suggest running convention audit
EOF
  echo "✓ Kiro bridge: $KIRO_DIR/SKILL.md"
fi

echo ""
echo "Done. ${#ROWS[@]} skills indexed."
